# See https://symfony.com/doc/current/email/dev_environment.html
swiftmailer:
  # send all emails to a specific address
  #delivery_addresses: ['me@example.com']

  transport: smtp
  #auth_mode: login
  port:
  host:
  username:
  password:
  spool: { type: 'memory' }
